org: yaritzalopez
service: customer-serverless

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::635391287019:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_customers

functions:
  crear:
    handler: createCustomer.lambda_handler
    events:
      - http:
          path: /customer/crear
          method: post
          cors: true
          integration: lambda

  obtener:
    handler: getCustomer.lambda_handler
    events:
      - http:
          path: /customer/obtener
          method: post
          cors: true
          integration: lambda

  actualizar:
    handler: updateCustomer.lambda_handler
    events:
      - http:
          path: /customer/{customerID}
          method: put
          cors: true
          integration: lambda

  activar:
    handler: activateCustomer.lambda_handler
    events:
      - http:
          path: /customer/activar
          method: post
          cors: true
          integration: lambda

  desactivar:
    handler: deleteCustomer.lambda_handler
    events:
      - http:
          path: /customer/desactivar
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaClientes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: customer_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: customer_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
