org: yaritzalopez
service: customer-serverless

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::157918330129:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_customers

functions:
  crear:
    handler: createCustomer.lambda_handler
    events:
      - http:
          path: /customer/account/create
          method: post
          cors: true
          integration: lambda

  getCustomer:
    handler: getCustomer.lambda_handler
    events:
      - http:
          path: /customer/account/about
          method: get
          cors: true
          integration: lambda

  updateCustomer:
    handler: updateCustomer.lambda_handler
    events:
      - http:
          path: /customer/account/update
          method: put
          cors: true
          integration: lambda

  activateCustomer:
    handler: activateCustomer.lambda_handler
    events:
      - http:
          path: /customer/account/activate
          method: post
          cors: true
          integration: lambda

  deleteCustomer:
    handler: deleteCustomer.lambda_handler
    events:
      - http:
          path: /customer/account/delete
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaClientes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: customer_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: customer_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
              - IndexName: email-index
                KeySchema:
                  - AttributeName: email
                    KeyType: HASH
                Projection:
                  ProjectionType: ALL
